export const testIds = {
  trxListPage: {
    list: 'trx_list_page#transaction_list',
    trxItem: (id: string) => `trx_list_page#transaction_item_${id}`,
    shimmer: (idx: string | number) => `trx_list_page#loading_skeleton_${idx}`,
    sortButton: 'trx_list_page#sort_button',
    backdrop: 'trx_list_page#backdrop',
    searchInput: 'trx_list_page#search_input',
    senderBank: 'trx_list_page#sender_bank',
    beneficiaryName: 'trx_list_page#beneficiary_name',
    beneficiaryBank: 'trx_list_page#beneficiary_bank',
    amount: 'trx_list_page#amount',
    createdAt: 'trx_list_page#created_at',
    statusMarker: 'trx_list_page#status_marker',
  },
  trxDetailPage: {
    copyTrxIdButton: 'trx_detail_page#copy_button',
    closeButton: 'trx_detail_page#close_button',
    senderBank: 'trx_detail_page#sender_bank',
    beneficiaryName: 'trx_detail_page#beneficiary_name',
    beneficiaryBank: 'trx_detail_page#beneficiary_bank',
    amount: 'trx_detail_page#amount',
    createdAt: 'trx_detail_page#created_at',
    uniqueCode: 'trx_detail_page#unique_code',
    remark: 'trx_detail_page#remark',
    status: 'trx_detail_page#status',
    accountNumber: 'trx_detail_page#account_number',
  },
};
